services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - monitoring_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment: # Ref: https://github.com/grafana/pyroscope/tree/main/examples/language-sdk-instrumentation/java/simple
      - GF_INSTALL_PLUGINS=grafana-pyroscope-app
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=127.0.0.1
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    networks:
      - monitoring_network

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: postgres_exporter
    environment:
      # 애플리케이션 서버의 실제 IP로 DB 연결 (지금은 로컬에서 설정중이라 호스트 IP로 연결중)
      DATA_SOURCE_NAME: "postgresql://user:password@host.docker.internal:5433/mydb?sslmode=disable"
    ports:
      - "9187:9187"
    networks:
      - monitoring_network

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:1.1.0
    container_name: nginx_exporter
    command: -nginx.scrape-uri http://host.docker.internal/stub_status
    ports:
      - "9113:9113"
    networks:
      - monitoring_network

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - loki_data:/loki
    networks:
      - monitoring_network

  pyroscope:
    image: grafana/pyroscope:latest
    container_name: pyroscope
    ports:
      - "4040:4040"
    volumes:
      - pyroscope_data:/var/lib/pyroscope
    networks:
      - monitoring_network

volumes:
  prometheus_data:
  grafana_data:
  loki_data:
  pyroscope_data:

networks:
  monitoring_network:
    driver: bridge
